build-steps:
    script:
        - echo "this is frist build step"
testing-job:
    script:
        - echo "frist step in testing"
        - echo "second step in testing"

deploy-job:
    script:
        - echo "frist step in deploy"
